### PR TITLE
Add support for passing complete data object

### PR DESCRIPTION
**Pull request by clnt**
Thanks for this package, its awesome and saved me a lot of time!

I've been porting a legacy application to a more modern codebase, in this the chart data is generated as an object with `cols` and `rows` properties. With this change I can dump my entire data object into the component and have it draw the chart :)

Example data object taken from the Google Chart docs:

```
{
    cols: [{id: 'task', label: 'Task', type: 'string'},
           {id: 'hours', label: 'Hours per Day', type: 'number'}],
    rows: [{c:[{v: 'Work'}, {v: 11}]},
           {c:[{v: 'Eat'}, {v: 2}]},
           {c:[{v: 'Commute'}, {v: 2}]},
           {c:[{v: 'Watch TV'}, {v:2}]},
           {c:[{v: 'Sleep'}, {v:7, f:'7.000'}]}]
}
```

https://developers.google.com/chart/interactive/docs/reference#datatable-class

### CODE REVIEW

**Comment by nobilix** [comment]
@clnt  thanks for your feedback!
This is implemented in the current version (0.3.0)

**Comment by clnt** [comment]
@nobilix Hi mate, no problem!

The reason I used `this.data === Object(this.data)` is because the `typeof` check will still equal `true` if you pass it `null`. If you pass `null` to that DataTable function it will attempt to draw a chart with no columns resulting in an error message being displayed on the page.

See: https://jsfiddle.net/ds6oh80e/7/

**Comment by nobilix** [comment]
`null` is not an issue in case of GCharts since it's falsy, this

**Comment by nobilix** [comment]
but `this.data === Object(this.data)` check allows functions too

I think we should check both:
`if (this.data !== null && typeof this.data === 'object') return new chartsLib.visualization.DataTable(this.data)`

@alexxlagutin please update ^

**Comment by clnt** [comment]
Sounds good :)

**Pull request closed without merging**
